package ru.alexsuvorov.employee_service.model;

import android.content.ContentValues;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import ru.alexsuvorov.employee_service.db.DBAdapter;

//Generated by http://www.jsonschema2pojo.org/
public class Employee implements Serializable {

    @SerializedName("f_name")
    @Expose
    private String f_name;
    @SerializedName("l_name")
    @Expose
    private String l_name;
    @SerializedName("birthday")
    @Expose
    private String birthday;
    @SerializedName("age")
    private int age;
    @SerializedName("avatr_url")
    @Expose
    private String avatarLink;
    private int specialty;
    @SerializedName("specialty")
    @Expose
    private final static long serialVersionUID = -8824149947485321362L;

    public String getF_name() {
        return f_name;
    }

    public void setF_name(String f_name) {
        char[] charFname = f_name.toCharArray();
        charFname[0] = Character.toUpperCase(charFname[0]);
        for (int i = 1; i < charFname.length; i++) {
            charFname[i] = Character.toLowerCase(charFname[i]);
        }
        this.f_name = new String(charFname);
    }

    public String getL_name() {
        return l_name;
    }

    public void setL_name(String l_name) {
        char[] charLname = l_name.toCharArray();
        charLname[0] = Character.toUpperCase(charLname[0]);
        for (int i = 1; i < charLname.length; i++) {
            charLname[i] = Character.toLowerCase(charLname[i]);
        }
        this.l_name = new String(charLname);
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getAvatarLink() {
        return avatarLink;
    }

    public void setAvatarLink(String avatrUrl) {
        this.avatarLink = avatrUrl;
    }

    /*public List<Specialty> getSpecialty() {
        return specialty;
    }*/

    /*public void setSpecialty(List<Specialty> specialty) {
        this.specialty = specialty;
    }*/

    public int getSpecialty() {
        return specialty;
    }

    public void setSpecialty(int specialty) {
        this.specialty = specialty;
    }

    public static ContentValues getContentValues(Employee employee) {
        ContentValues initialValues = new ContentValues();
        if (employee.getF_name() != null) {
            initialValues.put(DBAdapter.COLUMN_FNAME, employee.getF_name());
        }
        if (employee.getL_name() != null) {
            initialValues.put(DBAdapter.COLUMN_LNAME, employee.getL_name());
        }
        if (employee.getBirthday() != null) {
            initialValues.put(DBAdapter.COLUMN_BIRTHDAY, employee.getBirthday());
        }
        initialValues.put(DBAdapter.COLUMN_AGE, employee.getAge());
        if (employee.getAvatarLink() != null) {
            initialValues.put(DBAdapter.COLUMN_AVATARLINK, employee.getAvatarLink());
        }
        initialValues.put(DBAdapter.COLUMN_WSPECIALTY, employee.getSpecialty());
        return initialValues;
    }

    @Override
    public String toString() {
        return "Employee{" + '\'' +
                ", f_name='" + f_name + '\'' +
                ", l_name='" + l_name + '\'' +
                ", bithday='" + birthday + '\'' +
                ", age=" + age +
                ", avatarLink='" + avatarLink + '\'' +
                ", specialty=" + specialty +
                '}';
    }
}