package ru.alexsuvorov.employee_service.model;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;

//Generated by http://www.jsonschema2pojo.org/
//@Entity(indices = {@Index(value = {"specId", "specName"}, unique = false)})
@Entity/*(foreignKeys = @ForeignKey(entity = Employee.class,
        parentColumns = {"employeeId"},
        childColumns = {"specId"},
        onUpdate = CASCADE,
        onDelete = CASCADE))*/
public class Specialty {

    @PrimaryKey
    public int specialty_id;
    public String name;
    //public int employeeId;
    @Ignore
    public final static long serialVersionUID = 4288061416169200241L;

    public Specialty(int specialty_id, String name) {
        this.specialty_id = specialty_id;
        this.name = name;
    }

    @Ignore
    public Specialty() {
    }

    public int getSpecId() {
        return specialty_id;
    }

    public void setSpecId(int specialtyId) {
        this.specialty_id = specialtyId;
    }

    public String getSpecName() {
        return name;
    }

    public void setSpecName(String name) {
        this.name = name;
    }

    /*public int getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }*/



    /*
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Specialty specialty = (Specialty) o;
        if (specId != specialty.specId) return false;
        return specName != null ? specName.equals(specialty.specName) : specialty.specName == null;
    }
    @Override
    public int hashCode() {
        int result = specId;
        result = 31 * result + (specName != null ? specName.hashCode() : 0);
        return result;
    }
    @Override
    public String toString() {
        return "Specialty{" +
                "specId=" + specId +
                ", specName='" + specName + '\'' +
                '}';
    }*/
}