package ru.alexsuvorov.employee_service.model;

import android.content.ContentValues;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import ru.alexsuvorov.employee_service.db.DBAdapter;

//Generated by http://www.jsonschema2pojo.org/
public class Specialty implements Serializable {

    @SerializedName("specialty_id")
    @Expose
    private int specId;
    @SerializedName("name")
    @Expose
    private String specName;
    private final static long serialVersionUID = 4288061416169200241L;

    public Specialty(int specId, String specName) {
        this.specId = specId;
        this.specName = specName;
    }

    public int getSpecId() {
        return specId;
    }

    public void setSpecId(int specialtyId) {
        this.specId = specialtyId;
    }

    public String getSpecName() {
        return specName;
    }

    public void setSpecName(String name) {
        this.specName = name;
    }


    public static ContentValues getContentValues(Specialty specialty) {
        ContentValues initialValues = new ContentValues();
        initialValues.put(DBAdapter.COLUMN_SPECIALTY_ID, specialty.getSpecId());
        if (specialty.getSpecName() != null) {
            initialValues.put(DBAdapter.COLUMN_SPECIALTY_NAME, specialty.getSpecName());
        }
        return initialValues;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Specialty specialty = (Specialty) o;
        if (specId != specialty.specId) return false;
        return specName != null ? specName.equals(specialty.specName) : specialty.specName == null;
    }

    @Override
    public int hashCode() {
        int result = specId;
        result = 31 * result + (specName != null ? specName.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Specialty{" +
                "specId=" + specId +
                ", specName='" + specName + '\'' +
                '}';
    }
}