package ru.alexsuvorov.employee_service.model;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;

import java.io.Serializable;

//Generated by http://www.jsonschema2pojo.org/
//@Entity(indices = {@Index(value = {"specId", "specName"}, unique = false)})
@Entity/*(foreignKeys = @ForeignKey(entity = Employee.class,
        parentColumns = {"employeeId"},
        childColumns = {"specId"},
        onUpdate = CASCADE,
        onDelete = CASCADE))*/
public class Specialty implements Serializable {

    @PrimaryKey
    @ColumnInfo(name = "specialty_id")
    public int specialty_id;
    @ColumnInfo(name = "specialty_name")
    public String name;
    @ColumnInfo(name = "employeeOwner_id")
    public int employeeId;
    @Ignore
    public final static long serialVersionUID = 4288061416169200241L;

    public Specialty(int specialty_id, String name, int employeeId) {
        this.specialty_id = specialty_id;
        this.name = name;
        this.employeeId = employeeId;
    }

    @Ignore
    public Specialty() {
    }

    public int getSpecId() {
        return specialty_id;
    }

    public void setSpecId(int specialtyId) {
        this.specialty_id = specialtyId;
    }

    public String getSpecName() {
        return name;
    }

    public void setSpecName(String name) {
        this.name = name;
    }

    public int getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Specialty specialty = (Specialty) o;
        if (specialty_id != specialty.specialty_id) return false;
        return name != null ? name.equals(specialty.name) : specialty.name == null;
    }
    @Override
    public int hashCode() {
        int result = specialty_id;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
    @Override
    public String toString() {
        return "Specialty{" +
                "specId=" + specialty_id +
                ", specName='" + name + '\'' +
                '}';
    }
}